### PR TITLE
update sandbox.config node version for code-sandbox to pick up

### PR DESCRIPTION
**Pull request by scottander**
Updates to use the newest web sdk version.
Updates widget wrapper to use web's sdk wrapper.
Update custom service to use esri's new rest pattern
Various typing fixes

https://codesandbox.io/s/github/geocortex/vertigis-web-samples/tree/master/samples/arcgis-widget/
vs
https://codesandbox.io/s/github/geocortex/vertigis-web-samples/tree/node-version/samples/arcgis-widget/

### CODE REVIEW

**Review by eric-parsons — APPROVED** [review]

**Comment by KayaOM** [comment]
**Issue 1**: 

Load: https://codesandbox.io/s/github/geocortex/vertigis-web-samples/tree/node-version/samples/arcgis-widget/

image

**Comment by KayaOM** [comment]
**Question 2**

image

Now getting this even when viewing in an incognito browser. Is this to be expected?

**Comment by scottander** [comment]
All typing issues should now be fixed.

**Comment by KayaOM** [comment]
Confirmed fixes. No other issues found.

**Review by eric-parsons — APPROVED** [review]

**Pull request merged**
